

HTTP/1.1 500  - Internal Server Error
x-powered-by: Express
x-request-id: 546ea1ef-83b7-4daf-86f5-7c38a5e23aab
x-correlation-id: 546ea1ef-83b7-4daf-86f5-7c38a5e23aab
x-correlationid: 546ea1ef-83b7-4daf-86f5-7c38a5e23aab
content-type: application/json; charset=utf-8
content-length: 367
etag: W/"16f-2uS5rs7LGoWl0uRk773nOdxEKFQ"
date: Thu, 28 Mar 2024 15:34:45 GMT
connection: close
###

###

###
@host=localhost
@port=4004
@protocol=http

POST  {{protocol}}://{{host}}:{{port}}/odata/v2/dms-srv/MediaFile   HTTP/1.1
Content-Type: application/pdf
slug: invoice.pdf

< ./invoice.pdf
###
@host=localhost
@port=4004
@protocol=http
GET   {{protocol}}://{{host}}:{{port}}/odata/v2/dms-srv/MediaFile(guid'1f625369-0294-47c4-bc0a-6755ddc31b8d')/$value  HTTP/1.1